video_capture_source: 1
show_capture_video: false
splits:
- path: data/peachtrigger.png
  x: 565
  y: 517
  width: 82
  height: 109
  command_name: split
- path: data/w7trigger.png
  x: 754
  y: 566
  width: 207
  height: 38
  command_name: split