video_capture_source: 1
show_capture_video: false
splits:
- path: data/peachtrigger.png
  x: 565
  y: 517
  width: 82
  height: 109
- path: data/w7trigger.png
  x: 756
  y: 567
  width: 209
  height: 41